### PR TITLE
General progress bar

### PR DESCRIPTION
**Pull request by AngelGallegosE**

### CODE REVIEW

**Comment by alexismellamo** [comment]
Good work @AngelGallegosE, looking gooooooood man!

 But... it would be nice if the bar disappear when is not used, right? any thoughts? Let's see how others progress bar work, if they are always there or only when they are need, plz answer

**Comment by AngelGallegosE** [comment]
Sure, the bar should disappear. I will fix it.

**Comment by alexismellamo** [comment]
You're the man @AngelGallegosE

**Comment by AngelGallegosE** [comment]
Done

**Comment by alexismellamo** [comment]
Fine 👍 :1st_place_medal: 💯 🔢

**Pull request merged**
